version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=countdown_api_dev
      - GOSU_VERSION=1.17
      - LANG=en_US.utf8
      - PG_MAJOR=17
      - PG_VERSION=17.4-1.pgdg120+2
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
